### PR TITLE
Yohoushi docker image

### PR DESCRIPTION
**Pull request by niku4i**
I created Yohoushi docker image. The image is here https://hub.docker.com/r/nikushi/yohoushi/ 

This pull request includes Dockerfile and the instruction to run containers. The main purpose of this docker image is providing a easy way for users to try out Yohoushi.

### CODE REVIEW

**Comment by sonots** [comment]
nice

**Comment by niku4i** [comment]
@sonots Can I merge this?

**Comment by sonots** [comment]
I did not check, but it is free to merge on your responsibility

**Comment by niku4i** [comment]
I'm not hurrying. I would like feedback from you:)

**Comment by niku4i** [comment]
Let me merge this.

**Pull request merged**
