### PR TITLE
rails 4.2.0

### PR DESCRIPTION
**Pull request by niku4i**
http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-1-to-rails-4-2

### CODE REVIEW

**Comment by niku4i** [comment]
@sonots sorry for being late. Now all tests become green. Could you check updates?

**Comment by sonots** [comment]
I'll check it later

**Comment by sonots** [comment]
checked! :100:

**Comment by niku4i** [comment]
Merged!

**Pull request merged**
